version: "3.3"
services:     
  auth:
    build: ./docker-kuber
    ports:
      - 7111:7111
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
